version: "3.0"
services:
  api:
    build: api
    ports:
      - target: 8081
        published: 8081
    networks:
      - api-network
  database:
    build: ./database
    expose:
      - 8080
    networks:
      - api-network

networks:
  api-network:
